### ISSUE TITLE
Enrollment issue of existing accounts

### ISSUE THREAD

**Issue by bgauchon-reply** [reply-fr/sustainable-personal-accounts#11]
With the last arrivals, I encountered 2 problems and had to open a case with AWS support to get back control of the account : 
- If the newly created account is enrolled BEFORE the root user finish the configuration ; you end in a stale state where you lose all perms from both sides and can't remove account from organisation due to billing info not completed.
>> Accounts should be created from the Account factory only. Else, setup must be completed and CTExecution Role manually created in the account (pb occured whith saad account).
- In some cases, you have to create manually CTExecution Role manually. This happen if the account was used prior to enrollment or was in another organisation before (you have to change the org id in the trust relationship)

**Comment by bernard357** [comment]
this has been mentioned in the documentation coming with SPA - do use the Service Catalog to create accounts, and do not import accounts
