### ISSUE TITLE
prevent the creation of private hosted zone in Route53

### ISSUE THREAD

**Issue by bernard357** [reply-fr/sustainable-personal-accounts#110]
## What is this?
Change in SCP to prevent the creation of a private hosted zone in Route53

## Why is this important?
Private hosted zone are really expensive, and should be managed as shared deployments. 

## How to implement it?
- [ ] change SCP in production
- [ ] validate the behavior
- [ ] change sample SCP provided with SPA
- [ ] change workbook on preventive controls

**Comment by bernard357** [comment]
Thanks to Nassim Benmalek for reporting the issue

**Comment by bgauchon-reply** [comment]
Hello,
I don't have the feeling private hosted zone are expensive :
(ref [aws](https://aws.amazon.com/route53/pricing/?nc1=h_ls)
## Zones :
$0.50 per hosted zone / month for the first 25 hosted zones
$0.10 per hosted zone / month for additional hosted zones
## Queries (STD) :
$0.40 per million queries – first 1 Billion queries / month
$0.20 per million queries – over 1 Billion queries / month

Furthermore private hosted zone are a mandatory element for a lot of tests/behaviors based on internal naming of computer ; for example in Microsoft domains environments

**Comment by bernard357** [comment]
this issue is dropped, as suggested by Bertrand
