### ISSUE TITLE
Prevent Amazon Bedrock models fine-tuning

### ISSUE THREAD

**Issue by nassim-reply** [reply-fr/sustainable-personal-accounts#122]
# Title: Prevent Amazon Bedrock models fine-tuning

## What is this?
Change in SCP to prevent the creation of custom models jobs in Amazon Bedrock.

## Why is this important?
Models fine-tuning could lead to expensive costs. Amazon Bedrock pricing needs some understanding of how AI/ML works. Until we get a broader experience using the service we should prevent the use of a potentially expensive feature such as model fine-tuning.

## How to implement it?

- [x]  add `bedrock:CreateModelCustomizationJob` in `SpaDenyCreationOfCostlyResources`
- [x]  Merge the change into main branch
- [x]  validate the behavior
- [x]  change sample SCP provided with SPA
- [x]  change workbook on preventive controls

**Comment by bernard357** [comment]
behaviour validated after tests on Oct-24
