### ISSUE TITLE
make setup install package locally , in a PATH which is not in $PATH

### ISSUE THREAD

**Issue by bgauchon-reply** [reply-fr/sustainable-personal-accounts#16]
... and so we encounter command not found error.

`make setup` execute this command : `npm install --save-dev @marp-team/marp-cli`
This install marp in `~/sustainable-personal-accounts/node_modules/.bin/marp` which of course is not part of $PATH

In order to fix problem we should either : 
- Expand path and source it for user
or
- Install globally which put binary in /usr/bin/ : `sudo npm install -g @marp-team/marp-cli`

**Comment by bernard357** [comment]
the command in Makefile is `npm install -g @marp-team/marp-cli --force` so I think this issue can be closed
