### ISSUE TITLE
Make setup errors

### ISSUE THREAD

**Issue by bgauchon-reply** [reply-fr/sustainable-personal-accounts#35]
Hello, on my side encountered :
```
ERROR: flake8 4.0.1 has requirement mccabe<0.7.0,>=0.6.0, but you'll have mccabe 0.7.0 which is incompatible.
```
and
```
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/aws-cdk'
```
while ```make setup``` due to prior cdk install I guess
When doing sudo make setup, the setup manage both downgrading of mcabe and cdk

**Comment by bernard357** [comment]
flake8 is now on version 5.0.4, with mccabe 0.7.0
