### ISSUE TITLE
NPM -g fails if not root in make setup

### ISSUE THREAD

**Issue by bgauchon-reply** [reply-fr/sustainable-personal-accounts#43]
In ```make setup``` :
```
	npm install -g aws-cdk@latest --force
...
	npm install -g @marp-team/marp-cli --force
```
fails with permission denied if not root (cause -g is global and /usr/lib/node_modules/ is not world writable neither all of modules)

**Comment by bernard357** [comment]
I believe the solution is to sudo before the make command setup - can this workaround close this issue?

**Comment by bernard357** [comment]
this issue is considered as close - please re-open it if there is some need for it
