### ISSUE TITLE
Prowler : Integrate this tool for regular scans

### ISSUE THREAD

**Issue by ghost** [reply-fr/sustainable-personal-accounts#50]
https://github.com/prowler-cloud/prowler

Prowler is a command line tool that helps you with AWS security assessment, auditing, hardening and incident response.

It follows guidelines of the CIS Amazon Web Services Foundations Benchmark (49 checks) and has more than 190 additional checks including related to GDPR, HIPAA, PCI-DSS, ISO-27001, FFIEC, SOC2 and others.

**Comment by bernard357** [comment]
Prowler has been integrated as a shell script that can be activated from reference buildspec used by SPA. Add an environment variable `WITH_PROWLER` in your settings on OU or on accounts where you want to run prowler on maintenance window. This has been pushed to production some months go.
