### ISSUE TITLE
The region used in the settings.yaml is no't used

### ISSUE THREAD

**Issue by SoulKyu** [reply-fr/sustainable-personal-accounts#54]
Even if you change the region configured on your setting.yaml, it won't use it.

It will use you region on your ~/.aws/config instead.

**Comment by bernard357** [comment]
this has been fixed in e79e5fc8b09427e100fa9d6d42d5be0fe2ba31bf

**Comment by bernard357** [comment]
Fixed in e79e5fc8b09427e100fa9d6d42d5be0fe2ba31bf
