### ISSUE TITLE
IAM Password Policy enforced by default

### ISSUE THREAD

**Issue by geoffroyrenaud** [reply-fr/sustainable-personal-accounts#96]
As recommended by the Trust Advisor, it's a best practice to enforce the IAM password policy.
In the SPA context I would suggest to add this AWS CLI command to the fixtures/buildspec/preparation_account_template.yaml :

aws iam update-account-password-policy --minimum-password-length 24 --require-numbers --require-uppercase-characters --require-lowercase-characters --require-symbols --max-password-age 90 --password-reuse-prevention 12 --hard-expiry

<img width="730" alt="image" src="https://user-images.githubusercontent.com/24882734/236603823-107adff3-fa86-42a3-bae2-dd5a527039f5.png">

**Comment by bernard357** [comment]
Pull request has been merged - thank you for this contribution :-)
